excluded:
  - Carthage
disabled_rules:
  - nesting
  - implicit_getter
line_length:
  warning: 150
  error: 175
  ignores_comments: true
type_name:
  max_length:
    warning: 60
    error: 60
identifier_name:
  allowed_symbols: "_"
  max_length:
    warning: 60
    error: 60
  min_length:
    warning: 1
